# Generated by Django 5.1 on 2024-09-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create_data',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='last_edit_data',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата производства продукта'),
        ),
    ]
